"""
generate_report.py
Automated financial analysis report: reads statements, calculates ratios
and cash flow metrics, generates charts, and writes a summary Markdown report.
"""
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

from financial_ratios import calculate_ratios
from cash_flow_analysis import analyze_cash_flow

plt.rcParams.update({'font.size': 10, 'font.family': 'DejaVu Sans'})

OUT_DIR = '/home/claude/python_project'

df = pd.read_csv(f'{OUT_DIR}/financial_statements.csv')
ratios = calculate_ratios(df)
cf = analyze_cash_flow(df)

years = df['Year']

# ---------- Chart 1: Revenue & Net Income Trend ----------
fig, ax1 = plt.subplots(figsize=(8, 5))
ax1.bar(years, df['Revenue'], color='#1F4E78', alpha=0.85, label='Revenue')
ax1.set_ylabel('Revenue (\u00a3 thousands)', color='#1F4E78')
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'\u00a3{x:,.0f}'))
ax2 = ax1.twinx()
ax2.plot(years, df['Net_Income'], color='#C00000', marker='o', linewidth=2.5, label='Net Income')
ax2.set_ylabel('Net Income (\u00a3 thousands)', color='#C00000')
ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'\u00a3{x:,.0f}'))
plt.title('Revenue & Net Income Trend (FY2022A\u2013FY2026E)', fontweight='bold')
fig.tight_layout()
plt.savefig(f'{OUT_DIR}/chart1_revenue_netincome.png', dpi=150)
plt.close()

# ---------- Chart 2: Margin Trends ----------
fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(years, ratios['Gross_Margin_%'], marker='o', label='Gross Margin %', color='#1F4E78', linewidth=2.5)
ax.plot(years, ratios['Net_Margin_%'], marker='o', label='Net Margin %', color='#C00000', linewidth=2.5)
ax.plot(years, ratios['ROE_%'], marker='o', label='ROE %', color='#548235', linewidth=2.5)
ax.set_ylabel('%')
ax.set_title('Profitability Trends (FY2022A\u2013FY2026E)', fontweight='bold')
ax.legend()
ax.grid(alpha=0.3)
fig.tight_layout()
plt.savefig(f'{OUT_DIR}/chart2_margins.png', dpi=150)
plt.close()

# ---------- Chart 3: Liquidity & Leverage ----------
fig, ax1 = plt.subplots(figsize=(8, 5))
ax1.plot(years, ratios['Current_Ratio'], marker='o', color='#1F4E78', linewidth=2.5, label='Current Ratio')
ax1.plot(years, ratios['Quick_Ratio'], marker='o', color='#2E75B6', linewidth=2.5, label='Quick Ratio')
ax1.axhline(1.0, color='gray', linestyle='--', linewidth=1, alpha=0.6)
ax1.set_ylabel('Ratio (x)')
ax2 = ax1.twinx()
ax2.plot(years, ratios['Debt_to_Equity'], marker='s', color='#C00000', linewidth=2.5, label='Debt-to-Equity')
ax2.set_ylabel('Debt-to-Equity (x)', color='#C00000')
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left')
plt.title('Liquidity & Leverage Trends', fontweight='bold')
fig.tight_layout()
plt.savefig(f'{OUT_DIR}/chart3_liquidity_leverage.png', dpi=150)
plt.close()

# ---------- Chart 4: Free Cash Flow ----------
fig, ax = plt.subplots(figsize=(8, 5))
width = 0.35
x = range(len(years))
ax.bar([i - width/2 for i in x], cf['CFO'], width, label='Operating Cash Flow', color='#1F4E78')
ax.bar([i + width/2 for i in x], cf['Free_Cash_Flow'], width, label='Free Cash Flow', color='#70AD47')
ax.set_xticks(list(x))
ax.set_xticklabels(years)
ax.set_ylabel('\u00a3 thousands')
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f'\u00a3{v:,.0f}'))
ax.set_title('Operating Cash Flow vs. Free Cash Flow', fontweight='bold')
ax.legend()
fig.tight_layout()
plt.savefig(f'{OUT_DIR}/chart4_cashflow.png', dpi=150)
plt.close()

print("4 charts generated successfully.")

# ---------- Automated Markdown Report ----------
latest = ratios.iloc[-1]
first = ratios.iloc[0]
latest_cf = cf.iloc[-1]

report = f"""# Automated Financial Analysis Report
**Company:** Illustrative UK FMCG Distribution Business
**Period:** {years.iloc[0]} \u2013 {years.iloc[-1]}
**Generated by:** `generate_report.py` (Python, pandas, matplotlib)

---

## Executive Summary

Over the {len(years)}-year period, revenue grew from \u00a3{df['Revenue'].iloc[0]:,.0f}K to \u00a3{df['Revenue'].iloc[-1]:,.0f}K
({(df['Revenue'].iloc[-1]/df['Revenue'].iloc[0]-1)*100:.1f}% cumulative growth), while net margin expanded from
{first['Net_Margin_%']:.1f}% to {latest['Net_Margin_%']:.1f}%. The business has consistently converted
{cf['FCF_to_Net_Income_%'].mean():.0f}% of net income into free cash flow on average, indicating high earnings quality.

## Key Ratios ({years.iloc[-1]})

| Metric | Value | Trend vs {years.iloc[0]} |
|---|---|---|
| Gross Margin | {latest['Gross_Margin_%']:.1f}% | {'+' if latest['Gross_Margin_%']>first['Gross_Margin_%'] else ''}{latest['Gross_Margin_%']-first['Gross_Margin_%']:.1f}pp |
| Net Margin | {latest['Net_Margin_%']:.1f}% | {'+' if latest['Net_Margin_%']>first['Net_Margin_%'] else ''}{latest['Net_Margin_%']-first['Net_Margin_%']:.1f}pp |
| ROE | {latest['ROE_%']:.1f}% | {'+' if latest['ROE_%']>first['ROE_%'] else ''}{latest['ROE_%']-first['ROE_%']:.1f}pp |
| Current Ratio | {latest['Current_Ratio']:.2f}x | {'+' if latest['Current_Ratio']>first['Current_Ratio'] else ''}{latest['Current_Ratio']-first['Current_Ratio']:.2f}x |
| Debt-to-Equity | {latest['Debt_to_Equity']:.2f}x | {latest['Debt_to_Equity']-first['Debt_to_Equity']:.2f}x |
| Cash Conversion Cycle | {latest['Cash_Conversion_Cycle_days']:.0f} days | {latest['Cash_Conversion_Cycle_days']-first['Cash_Conversion_Cycle_days']:.0f} days |

## Cash Flow Highlights ({years.iloc[-1]})
- Operating Cash Flow: \u00a3{latest_cf['CFO']:,.0f}K
- Free Cash Flow: \u00a3{latest_cf['Free_Cash_Flow']:,.0f}K
- FCF Margin: {latest_cf['FCF_Margin_%']:.1f}%
- Cash Balance: \u00a3{latest_cf['Cash_Balance']:,.0f}K

## Charts
![Revenue and Net Income](chart1_revenue_netincome.png)
![Margins](chart2_margins.png)
![Liquidity and Leverage](chart3_liquidity_leverage.png)
![Cash Flow](chart4_cashflow.png)

## Key Insight
The current ratio crossed above 1.0x in {years[ratios['Current_Ratio'] >= 1.0].iloc[0] if (ratios['Current_Ratio'] >= 1.0).any() else 'N/A'},
marking a shift from a working-capital-constrained to a working-capital-healthy position \u2014
consistent with the improving cash conversion cycle and falling leverage over the same period.
"""

with open(f'{OUT_DIR}/financial_analysis_report.md', 'w') as f:
    f.write(report)

print("Report generated: financial_analysis_report.md")
